# Generated by Django 2.0.5 on 2018-07-19 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sponsor', models.CharField(max_length=100)),
                ('start_date', models.DateField(verbose_name='Date exhibition starts')),
                ('end_date', models.DateField(verbose_name='Date exhibition ends')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Item description')),
                ('item_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=50, verbose_name='Day or Night shift')),
                ('works_in', models.ManyToManyField(to='exhibitions.Gallery')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exhibitions.Item')),
                ('country_origin', models.CharField(max_length=100)),
                ('excavation_site', models.CharField(max_length=150)),
                ('discovery_year', models.IntegerField(verbose_name='Year artifact was discovered')),
                ('condition', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
            ],
            bases=('exhibitions.item',),
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exhibitions.Item')),
                ('art_type', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
            bases=('exhibitions.item',),
        ),
        migrations.CreateModel(
            name='Fossil',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exhibitions.Item')),
                ('country_origin', models.CharField(max_length=100)),
                ('excavation_site', models.CharField(max_length=150)),
                ('discovery_year', models.IntegerField(verbose_name='Year fossil was discovered')),
                ('period', models.CharField(max_length=50)),
            ],
            bases=('exhibitions.item',),
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exhibitions.Item')),
                ('scientific_name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
            ],
            bases=('exhibitions.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitions.Exhibition'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitions.Gallery'),
        ),
    ]
