# Generated by Django 2.0.5 on 2018-07-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Preserved'), (2, 'Fair'), (3, 'Damaged')]),
        ),
    ]
