# Generated by Django 2.0.5 on 2018-07-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_auto_20180719_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.AlterField(
            model_name='organism',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Taxidermied')]),
        ),
    ]
